accounts/urls.py
"""Defines URL patterns for accounts"""

from django.urls import path, include

from . import views

app_name = 'accounts'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),

    # Registration page.
    path('register/', views.register, name='register'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('main_blog.urls')),
]

main_blog/urls.py
"""Defines URL patterns for main_blog"""

from django.urls import path

from . import views

app_name = 'main_blog'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),

    # Page that shows all posts.
    path('posts/', views.posts, name='posts'),

    # Show a post and their comments.
    path('post/<int:post_id>/', views.post, name='post'),

    # Page for adding a new post.
    path('new_post/', views.new_post, name='new_post'),

    # Page for adding a new comment.
    path('new_comment/<int:post_id>/', views.new_comment, name='new_comment'),

    # Page for editing a comment.
    path('edit_comment/<int:comment_id>/', views.edit_comment, name='edit_comment'),
]

accounts/models.py
from django.db import models

# Create your models here.

main_blog/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    """A post posted by the user"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.text
    
    
class Comment(models.Model):
    """Add a comment"""
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        if len(self.text) < 50:
            return self.text
        else:
            return f"{self.text[:50]}..."

main_blog/forms.py
from django import forms

from .models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['text']
        labels = {'text': ''}

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    """Register a new user."""
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page.
            login(request, new_user)

            return redirect('main_blog:index')
        
    # Display a blank or invalid form.
    return render(request, 'registration/register.html', {'form': form})

main_blog/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Post, Comment
from .forms import PostForm, CommentForm

def index(request):
    """The home page for main_blog"""

    return render(request, 'main_blog/index.html')

@login_required
def posts(request):
    """Show all posts"""

    posts = Post.objects.filter(owner=request.user).order_by('date_added')

    return render(request, 'main_blog/posts.html', {
        'posts': posts
    })

@login_required
def post(request, post_id):
    """Show a single post and its comments."""
    post = Post.objects.get(id=post_id)
    # Make sure a post belongs to the current user.
    if post.owner != request.user:
        raise Http404
    
    comments = post.comment_set.order_by('-date_added')

    return render(request, 'main_blog/post.html', {
        'post': post,
        'comments': comments
    })

@login_required
def new_post(request):
    """Add a new post."""
    if request.method != 'POST':
        # Create a blank form
        form = PostForm()
    else:
        # Process data.
        form = PostForm(data=request.POST)

        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.owner = request.user
            new_post.save()
            
            return redirect('main_blog:posts')
    
    # Display a blank or invalid form
    return render(request, 'main_blog/new_post.html', {
        'form': form
    })

@login_required
def new_comment(request, post_id):
    """Add a new comment for a particular post."""
    post = Post.objects.get(id=post_id)

    # Make sure a post belongs to the current user.
    if post.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # Create a blank form
        form = CommentForm()
    else:
        # Process data.
        form = CommentForm(data=request.POST)

        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.post = post
            new_comment.save()
            return redirect('main_blog:post', post_id=post_id)
    
    # Display a blank or invalid form
    return render(request, 'main_blog/new_comment.html', {
        'form': form,
        'post': post,
    })

@login_required
def edit_comment(request, comment_id):
    """Edit a comment."""
    comment = Comment.objects.get(id=comment_id)
    post = comment.post

    # Make sure a post belongs to the current user.
    if post.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # Pre-fill form with current comment.
        form = CommentForm(instance=comment)
    else:
        # Process data.
        form = CommentForm(instance=comment, data=request.POST)

        if form.is_valid():
            form.save()
            return redirect('main_blog:post', post_id=post.id)
    
    # Display a blank or invalid form
    return render(request, 'main_blog/edit_comment.html', {
        'form': form,
        'post': post,
        'comment': comment,
    })

main_blog/templates/main_blog/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <title>{% block title %}{% endblock %}</title> 
        {% load django_bootstrap5 %}
        {% bootstrap_css %}
        {% bootstrap_javascript %}            		        
    </head>
    <body>
        <header class="d-md-flex header">
            {% block header %}
            <div class="col-12 d-flex justify-content-center align-items-center pt-5 p-xl-0">
                <h2 class="pt-5 p-xl-0">Personal Blog</h2>
            </div>                
            {% endblock header %}                        
        </header>
        <main class="container-fluid">            
            {% block nav %}
            <nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
                <div class="container-fluid">
                    <div class="col-5 col-sm-1 col-md-2 col-lg-2 col-xl-1">
                        <a class="navbar-brand" href=""><img src="" class="img-fluid float-start" alt="imagen_logo"></a>								
                    </div>							
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#my_nav" aria-controls="my_nav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="my_nav">
                        <ul class="nav navbar-nav justify-content-center w-100">                            
                            <li class="nav-item d-lg-inline-block">
                                <a class="nav-link" href="{% url "main_blog:index" %}">Home</a>
                            </li>
                            <li class="nav-item d-lg-inline-block">
                                <a class="nav-link" href="{% url "main_blog:posts" %}">Posts</a>
                            </li>
                            {% if user.is_authenticated %}
                            <li class="nav-item d-lg-inline-block">
                                <form action="{% url "accounts:logout" %}" method="post">
                                    {% csrf_token %}
                                    <button class='btn btn-link nav-link' name='submit'>Logout</button>
                                </form>
                            </li>
                            {% else %}
                            <li class="nav-item d-lg-inline-block">
                                <a class="nav-link" href="{% url "accounts:register" %}">Register</a>
                            </li> 
                            <li class="nav-item d-lg-inline-block">
                                <a class="nav-link" href="{% url "accounts:login" %}">Login</a>
                            </li>  
                            {% endif %}                                                                                  
                        </ul>
                    </div>																					
                </div>
            </nav>
            {% endblock nav %} 
            {% if user.is_authenticated %}
            <p>Welcome {{ user|capfirst }}</p>
            {% endif %}                       
            {% block content %}{% endblock content %}           
        </main>	
        {% block footer %}
        <footer class="container-fluid d-flex justify-content-center align-items-center">
            <p>Django course</p>
        </footer>
        {% endblock footer %}        
    </body>
</html>

main_blog/templates/main_blog/edit_comment.html
{% extends "./base.html" %}

{% block content %}
    <p><a href="{% url "main_blog:post" post.id %}">{{ post }}</a></p>

    <p>Edit comment:</p>
    <form action="{% url "main_blog:edit_comment" comment.id %}" method="post">
        {% csrf_token %}
        {{ form.as_div }}
        <button name='submit'>Save changes</button>
    </form>
{% endblock content %}

main_blog/templates/main_blog/index.html
{% extends "./base.html" %}

{% block content %}
    <h3>Home page</h3>
    <p>This is the home page</p>
{% endblock content %}

main_blog/templates/main_blog/new_comment.html
{% extends "./base.html" %}

{% block content %}
<p><a href="{% url "main_blog:post" post.id %}">{{ post }}</a></p>

<p>Add a new comment:</p>
<form action="{% url "main_blog:new_comment" post.id %}" method="post">
    {% csrf_token %}
    {{ form.as_div }}
    <button name='submit'>Add comment</button>
</form>
{% endblock content %}

main_blog/templates/main_blog/new_post.html
{% extends "./base.html" %}

{% block content %}
    <p>Add a new post:</p>

    <form action="{% url "main_blog:new_post" %}" method="post">
        {% csrf_token %}
        {{ form.as_div }}

        <button name="submit">Add Post</button>
    </form>
{% endblock content %}

main_blog/templates/main_blog/post.html
{% extends "./base.html" %}

{% block content %}
    <div class="col-5 mx-auto">
        <h3>Post: {{ post.text }}</h3>

        <p>Comments:</p>
        <p><a href="{% url "main_blog:new_comment" post.id %}">Add new comment</a></p>
    </div>    
        {% for comment in comments %}
            <div class="col-5 mx-auto card mb-3">
                <h5 class="card-header">
                    {{ comment.date_added|date:'d M, Y H:i' }}
                    <small><a href="{% url "main_blog:edit_comment" comment.id %}">Edit comment</a></small>
                </h5>
                <div class="card-body">
                    {{ comment.text|linebreaks }}
                </div>
            </div>            
        {% empty %}
            <p>There are no comments for this post yet.</p>
        {% endfor %}    
{% endblock content %}

main_blog/templates/main_blog/posts.html
{% extends "./base.html" %}

{% block content %}
    <h3>Posts view</h3>

    <ul>
        {% for post in posts %}
            <li><a href="{% url "main_blog:post" post.id %}">{{ post.text }}</a></li>
        {% empty %}
            <li>No posts have been added yet.</li>
        {% endfor %}
    </ul>

    <a href="{% url "main_blog:new_post" %}">Add a new post</a>
{% endblock content %}